# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # Define the available controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    fr_ft_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    leg_joint_controller:
      type: leg_joint_controller/LegJointController

#    unitree_sdk2_adapter:
#      type: westonrobot/UnitreeSdk2Adapter

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"

fr_ft_sensor_broadcaster:
  ros__parameters:
    sensor_name: "fr_ft_sensor"
    frame_id: "FR_foot_fixed"
#    interface_names:
#      force:
#        x: "force_torque_sensor_broadcaster/fr_ft_sensor/force.x"
#        y: "force_torque_sensor_broadcaster/fr_ft_sensor/force.y"
#        z: "force_torque_sensor_broadcaster/fr_ft_sensor/force.z"
#      torque:
#        x: "force_torque_sensor_broadcaster/fr_ft_sensor/torque.x"
#        y: "force_torque_sensor_broadcaster/fr_ft_sensor/torque.y"
#        z: "force_torque_sensor_broadcaster/fr_ft_sensor/torque.z"

leg_joint_controller:
  ros__parameters:
    update_rate: 1000  # Hz
    joints:
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

#unitree_sdk2_adapter:
#  ros__parameters:
#    command_prefix: "leg_pd_controller"
#    joints:
#      - FR_hip_joint
#      - FR_thigh_joint
#      - FR_calf_joint
#      - FL_hip_joint
#      - FL_thigh_joint
#      - FL_calf_joint
#      - RR_hip_joint
#      - RR_thigh_joint
#      - RR_calf_joint
#      - RL_hip_joint
#      - RL_thigh_joint
#      - RL_calf_joint
#    command_interfaces:
#      - effort
#      - position
#      - velocity
#      - kp
#      - kd
#    state_interfaces:
#      - effort
#      - position
#      - velocity
#    imu_name: "imu_sensor"
#    imu_interfaces:
#      - orientation.w
#      - orientation.x
#      - orientation.y
#      - orientation.z
#      - angular_velocity.x
#      - angular_velocity.y
#      - angular_velocity.z
#      - linear_acceleration.x
#      - linear_acceleration.y
#      - linear_acceleration.z
